# Presentación {-#Presenta}

Bienvenidos a la primera edición en línea e interactiva del Boletín Estadístico de la Universidad Nacional de Colombia [Sede Orinoquia](http://orinoquia.unal.edu.co/), un sitio web con la información y las cifras más representativas del desarrollo de la función misional representada en los procesos de formación, investigación y extensión desde el 2008 a la fecha, así como estadísticas resultantes del proceso de Gestión y Fomento Socioeconómico en el marco de las acciones de Bienestar Universitario. 

Con esta boletín estadístico se pretende cumplir con dos objetivos; el primero orientado a mantener registros actualizados y periódicos de algunas de las variables más importantes de la función misional de la sede como base de consulta para docentes, funcionarios, partes interesadas y comunidad en general. El segundo objetivo pretende facilitar la toma de decisiones que permita concretar la visión estratégica de la Institución de una forma coherente, metódica y eficaz, teniendo en cuenta que se hace necesaria la medición de la gestión y el desempeño como parte de los procesos de autoevaluación institucional.

Agradezco a todas los procesos que aportaron la información para la construcción de este boletín. Los comentarios o sugerencias relacionados con esta publicación pueden ser enviados a los correos  electrónicos  **siga_ori@unal.edu.co** o **planeación_ori@unal.edu.co**  

</br>

Cordialmente,


**OSCAR EDUARDO SUAREZ MORENO**</br>
Director Sede Orinoquia